spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to NabaBank cards related qa APIs"
  contactDetails:
    name: "Naba-qa Developer"
    email: "nabatech.qa.com.bd"
  onCallSupport:
    - "+88017234575"
    - "+88018267899"
