services:
  accounts:
    image: "nabatech/accounts:a1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nababank
  loans:
    image: "nabatech/loans:l1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nababank
  cards:
    image: "nabatech/cards:c1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - nababank
networks:
  nababank:
    driver: "bridge"
