spring:
  config:
    activate:
      on--profile: "prod"

build:
  version: "3.0"


loans:
  message: "Welcome to NabaBank loans related prod APIs"
  contactDetails:
    name: "Naba-prod developer"
    email: "nabatech.prod.com.bd"
  onCallSupport:
    - "+88017234575"
    - "+88018267899"