spring:
  config:
    activate:
      on--profile: "qa"

build:
  version: "2.0"


loans:
  message: "Welcome to NabaBank loans related qa APIs"
  contactDetails:
    name: "Naba-QA developer"
    email: "nabatech.qa.com.bd"
  onCallSupport:
    - "+88017234575"
    - "+88018267899"