server:
  port: 9000
spring:
  application:
    name: cards

build:
  version: "1.0"

cards:
  message: "Welcome to NabaBank cards related local APIs"
  contactDetails:
    name: "Naba-developer"
    email: "nabatech.com.bd"
  onCallSupport:
    - "+88017234509875"
    - "+88018234567899"