spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "E:\\Spring Project\\microservcie\\config"
        # search-locations: "classpath:/config"

server:
  port: 8071

