build:
  version: "2.0"


accounts:
  message: "Welcome to NabaBank accounts related qa APIs"
  contactDetails:
    name: "Naba-qa developer"
    email: "nabatech.qa.com.bd"
  onCallSupport:
    - "+88017234575"
    - "+88018267899"